spring:
  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url: "jdbc:h2:mem:test"
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always
jwt:
  key: "eavjaebvjaebvjaekjaekvnaejvnkjaejkjfnakjebvjeab"
  expiration: 5