version: '1.0'
name: house-pricing-analysis

services:
  backend:
    build: 
      context: ./backend/IntegracjaSystemow
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 8080:8080
    dns:
      - 8.8.8.8
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=${DB_URL}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_KEY=${JWT_KEY}
    container_name: backend
  frontend:
    build: 
      context: ./frontend/IntegracjaSystemow_frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    container_name: frontend
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=house-pricing